#ifndef SLICOT_CONFIG_H
#define SLICOT_CONFIG_H

/**
 * @file slicot_config.h
 * @brief Build configuration for SLICOT C library
 *
 * This file is generated by CMake during configuration.
 * Do not edit directly - edit slicot_config.h.in instead.
 */

/* BLAS/LAPACK symbol naming convention */
#define SLC_FC_LOWER_US
/* #undef SLC_FC_LOWER */
/* #undef SLC_FC_UPPER */

/* ILP64 support (64-bit integers for BLAS/LAPACK) */
/* #undef SLICOT_ILP64 */

/* Version information */
#define SLICOT_VERSION_MAJOR 0
#define SLICOT_VERSION_MINOR 1
#define SLICOT_VERSION_PATCH 0

#endif /* SLICOT_CONFIG_H */
